package com.project.game.dto;

public class QnADTO {
    private int gameNo;
    private String gameTitle;
    private String gameContent;
    private String gameWriter;
    private String gameDate;
    private int gameHits;
    private int game;

}
번호 글제목 작성자 날짜 조회수 추천
CREATE TABLE LOL_QNA(
        GAME_NO NUMBER GENERATED BY DEFAULT AS IDENTITY,
        GAME_TITLE VARCHAR2(100) NOT NULL,
GAME_CONTENT VARCHAR2(200) NOT NULL,
GAME_WRITER VARCHAR2(100) NOT NULL,
GAME_DATE DATE DEFAULT SYSDATE,
GAME_hits NUMBER DEFAULT 0 NOT NULL,
GAME_recommend NUMBER DEFAULT 0 NOT NULL,
GAME_PASSWD VARCHAR2(18) NOT NULL,
CONSTRAINT LOL_QNA_PK PRIMARY KEY(GAME_NO)
);